"""initial schema

Revision ID: 8eed4d930259
Revises:
Created: 2026-08-10 14:32:31.750773
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import cairn.db.types

revision: str = "8eed4d930259"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("hosts", cairn.db.types.JsonText(), nullable=True),
        sa.Column("cookies_enc", sa.LargeBinary(), nullable=True),
        sa.Column("script_enc", sa.LargeBinary(), nullable=True),
        sa.Column("cookie_meta", cairn.db.types.JsonText(), nullable=True),
        sa.Column("minted_at", cairn.db.types.UtcDateTime(length=32), nullable=True),
        sa.Column("expires_at", cairn.db.types.UtcDateTime(length=32), nullable=True),
        sa.Column("fingerprint", sa.String(length=80), nullable=True),
        sa.Column("last_verified_at", cairn.db.types.UtcDateTime(length=32), nullable=True),
        sa.Column("last_verify_result", sa.String(length=32), nullable=True),
        sa.Column("verify_url", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", cairn.db.types.UtcDateTime(length=32), nullable=False),
        sa.Column("updated_at", cairn.db.types.UtcDateTime(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_profiles")),
        sa.UniqueConstraint("name", name=op.f("uq_access_profiles_name")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ts", cairn.db.types.UtcDateTime(length=32), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target", sa.String(length=255), nullable=True),
        sa.Column("detail", cairn.db.types.JsonText(), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_table(
        "engines",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("manifest", cairn.db.types.JsonText(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("installed_at", cairn.db.types.UtcDateTime(length=32), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_engines")),
    )
    op.create_table(
        "folders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", cairn.db.types.UtcDateTime(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["folders.id"],
            name=op.f("fk_folders_parent_id_folders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_folders")),
        sa.UniqueConstraint("parent_id", "slug", name="uq_folders_parent_slug"),
        sa.UniqueConstraint("path", name=op.f("uq_folders_path")),
    )
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ts", cairn.db.types.UtcDateTime(length=32), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("successful", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_login_attempts")),
    )
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.create_index("ix_login_attempts_ip_ts", ["ip", "ts"], unique=False)
        batch_op.create_index("ix_login_attempts_user_ts", ["username", "ts"], unique=False)

    op.create_table(
        "saved_views",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("query", cairn.db.types.JsonText(), nullable=False),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_views")),
        sa.UniqueConstraint("name", name=op.f("uq_saved_views_name")),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", cairn.db.types.JsonText(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("color", sa.String(length=16), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("name", name=op.f("uq_tags_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_tags_slug")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("totp_secret", sa.LargeBinary(), nullable=True),
        sa.Column("totp_confirmed", sa.Boolean(), nullable=False),
        sa.Column("recovery_codes", sa.LargeBinary(), nullable=True),
        sa.Column("created_at", cairn.db.types.UtcDateTime(length=32), nullable=False),
        sa.Column("last_login_at", cairn.db.types.UtcDateTime(length=32), nullable=True),
        sa.Column("failed_logins", sa.Integer(), nullable=False),
        sa.Column("locked_until", cairn.db.types.UtcDateTime(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", cairn.db.types.UtcDateTime(length=32), nullable=False),
        sa.Column("last_seen_at", cairn.db.types.UtcDateTime(length=32), nullable=False),
        sa.Column("expires_at", cairn.db.types.UtcDateTime(length=32), nullable=False),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("revoked_at", cairn.db.types.UtcDateTime(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index("ix_sessions_user", ["user_id"], unique=False)

    op.create_table(
        "sites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("folder_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("seed_url", sa.Text(), nullable=False),
        sa.Column("primary_host", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("profile_id", sa.Integer(), nullable=True),
        sa.Column("engine_id", sa.String(length=64), nullable=False),
        sa.Column("engine_config", cairn.db.types.JsonText(), nullable=False),
        sa.Column("keep_mirror", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("archive_path", sa.String(length=1024), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("url_count", sa.Integer(), nullable=False),
        sa.Column("last_capture_at", cairn.db.types.UtcDateTime(length=32), nullable=True),
        sa.Column("created_at", cairn.db.types.UtcDateTime(length=32), nullable=False),
        sa.Column("updated_at", cairn.db.types.UtcDateTime(length=32), nullable=False),
        sa.Column("deleted_at", cairn.db.types.UtcDateTime(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["folder_id"],
            ["folders.id"],
            name=op.f("fk_sites_folder_id_folders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["access_profiles.id"],
            name=op.f("fk_sites_profile_id_access_profiles"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sites")),
        sa.UniqueConstraint("archive_path", name=op.f("uq_sites_archive_path")),
        sa.UniqueConstraint("folder_id", "slug", name="uq_sites_folder_slug"),
    )
    with op.batch_alter_table("sites", schema=None) as batch_op:
        batch_op.create_index("ix_sites_folder", ["folder_id"], unique=False)
        batch_op.create_index("ix_sites_host", ["primary_host"], unique=False)

    op.create_table(
        "feeds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("interval_min", sa.Integer(), nullable=False),
        sa.Column("last_polled_at", cairn.db.types.UtcDateTime(length=32), nullable=True),
        sa.Column("last_success_at", cairn.db.types.UtcDateTime(length=32), nullable=True),
        sa.Column("etag", sa.String(length=255), nullable=True),
        sa.Column("last_modified", sa.String(length=64), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_feeds_site_id_sites"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feeds")),
        sa.UniqueConstraint("site_id", "url", name="uq_feeds_site_url"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("spec", cairn.db.types.JsonText(), nullable=False),
        sa.Column("progress", cairn.db.types.JsonText(), nullable=True),
        sa.Column("pid", sa.Integer(), nullable=True),
        sa.Column("queued_at", cairn.db.types.UtcDateTime(length=32), nullable=False),
        sa.Column("started_at", cairn.db.types.UtcDateTime(length=32), nullable=True),
        sa.Column("finished_at", cairn.db.types.UtcDateTime(length=32), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_jobs_site_id_sites"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index("ix_jobs_queue", ["status", "priority", "queued_at"], unique=False)

    op.create_table(
        "scope_patterns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("pattern", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_scope_patterns_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scope_patterns")),
    )
    with op.batch_alter_table("scope_patterns", schema=None) as batch_op:
        batch_op.create_index("ix_scope_patterns_site", ["site_id"], unique=False)

    op.create_table(
        "scope_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("crawl_pages", sa.Boolean(), nullable=False),
        sa.Column("fetch_assets", sa.Boolean(), nullable=False),
        sa.Column("path_prefix", sa.String(length=1024), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_scope_rules_site_id_sites"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scope_rules")),
        sa.UniqueConstraint("site_id", "host", name="uq_scope_rules_site_host"),
    )
    op.create_table(
        "site_tags",
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_site_tags_site_id_sites"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_site_tags_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("site_id", "tag_id", name=op.f("pk_site_tags")),
    )
    op.create_table(
        "captures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("engine_id", sa.String(length=64), nullable=False),
        sa.Column("engine_version", sa.String(length=64), nullable=True),
        sa.Column("dir_name", sa.String(length=255), nullable=False),
        sa.Column("started_at", cairn.db.types.UtcDateTime(length=32), nullable=False),
        sa.Column("finished_at", cairn.db.types.UtcDateTime(length=32), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("url_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("bytes_written", sa.Integer(), nullable=False),
        sa.Column("warc_files", cairn.db.types.JsonText(), nullable=True),
        sa.Column("indexed_at", cairn.db.types.UtcDateTime(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_captures_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_captures_site_id_sites"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_captures")),
        sa.UniqueConstraint("site_id", "dir_name", name="uq_captures_site_dir"),
    )
    with op.batch_alter_table("captures", schema=None) as batch_op:
        batch_op.create_index("ix_captures_site", ["site_id"], unique=False)

    op.create_table(
        "discoveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("started_at", cairn.db.types.UtcDateTime(length=32), nullable=False),
        sa.Column("finished_at", cairn.db.types.UtcDateTime(length=32), nullable=True),
        sa.Column("pages_fetched", sa.Integer(), nullable=False),
        sa.Column("urls_found", sa.Integer(), nullable=False),
        sa.Column("summary", cairn.db.types.JsonText(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_discoveries_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_discoveries_site_id_sites"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discoveries")),
    )
    with op.batch_alter_table("discoveries", schema=None) as batch_op:
        batch_op.create_index("ix_discoveries_site", ["site_id"], unique=False)

    op.create_table(
        "capture_urls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("capture_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("mime", sa.String(length=128), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("digest", sa.String(length=64), nullable=True),
        sa.Column("is_revisit", sa.Boolean(), nullable=False),
        sa.Column("fetched_at", cairn.db.types.UtcDateTime(length=32), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["capture_id"],
            ["captures.id"],
            name=op.f("fk_capture_urls_capture_id_captures"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capture_urls")),
    )
    with op.batch_alter_table("capture_urls", schema=None) as batch_op:
        batch_op.create_index("ix_curls_capture", ["capture_id"], unique=False)
        batch_op.create_index(
            "ix_curls_errors",
            ["capture_id"],
            unique=False,
            sqlite_where=sa.text("status_code >= 400 OR error IS NOT NULL"),
        )
        batch_op.create_index("ix_curls_url", ["url"], unique=False)

    op.create_table(
        "discovered_hosts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("discovery_id", sa.Integer(), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("registrable", sa.String(length=255), nullable=False),
        sa.Column("is_seed_host", sa.Boolean(), nullable=False),
        sa.Column("link_refs", sa.Integer(), nullable=False),
        sa.Column("asset_refs", sa.Integer(), nullable=False),
        sa.Column("distinct_urls", sa.Integer(), nullable=False),
        sa.Column("role_guess", sa.String(length=32), nullable=True),
        sa.Column("sample_urls", cairn.db.types.JsonText(), nullable=True),
        sa.ForeignKeyConstraint(
            ["discovery_id"],
            ["discoveries.id"],
            name=op.f("fk_discovered_hosts_discovery_id_discoveries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discovered_hosts")),
        sa.UniqueConstraint("discovery_id", "host", name="uq_discovered_hosts_discovery_host"),
    )
    op.create_table(
        "feed_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("feed_id", sa.Integer(), nullable=False),
        sa.Column("guid", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("published_at", cairn.db.types.UtcDateTime(length=32), nullable=True),
        sa.Column("first_seen_at", cairn.db.types.UtcDateTime(length=32), nullable=False),
        sa.Column("capture_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["capture_id"],
            ["captures.id"],
            name=op.f("fk_feed_items_capture_id_captures"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["feed_id"], ["feeds.id"], name=op.f("fk_feed_items_feed_id_feeds"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feed_items")),
        sa.UniqueConstraint("feed_id", "guid", name="uq_feed_items_feed_guid"),
    )
    # ### end Alembic commands ###

    # Expression-based index, added by hand: SQLAlchemy cannot reflect these on
    # SQLite, so autogenerate skips them (it warns about exactly this). The
    # audit log is only ever read newest-first, so the DESC matters.
    op.create_index("ix_audit_ts", "audit_log", [sa.text("ts DESC")], unique=False)


def downgrade() -> None:
    op.drop_index("ix_audit_ts", table_name="audit_log")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feed_items")
    op.drop_table("discovered_hosts")
    with op.batch_alter_table("capture_urls", schema=None) as batch_op:
        batch_op.drop_index("ix_curls_url")
        batch_op.drop_index(
            "ix_curls_errors", sqlite_where=sa.text("status_code >= 400 OR error IS NOT NULL")
        )
        batch_op.drop_index("ix_curls_capture")

    op.drop_table("capture_urls")
    with op.batch_alter_table("discoveries", schema=None) as batch_op:
        batch_op.drop_index("ix_discoveries_site")

    op.drop_table("discoveries")
    with op.batch_alter_table("captures", schema=None) as batch_op:
        batch_op.drop_index("ix_captures_site")

    op.drop_table("captures")
    op.drop_table("site_tags")
    op.drop_table("scope_rules")
    with op.batch_alter_table("scope_patterns", schema=None) as batch_op:
        batch_op.drop_index("ix_scope_patterns_site")

    op.drop_table("scope_patterns")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_jobs_queue")

    op.drop_table("jobs")
    op.drop_table("feeds")
    with op.batch_alter_table("sites", schema=None) as batch_op:
        batch_op.drop_index("ix_sites_host")
        batch_op.drop_index("ix_sites_folder")

    op.drop_table("sites")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_sessions_user")

    op.drop_table("sessions")
    op.drop_table("users")
    op.drop_table("tags")
    op.drop_table("settings")
    op.drop_table("saved_views")
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.drop_index("ix_login_attempts_user_ts")
        batch_op.drop_index("ix_login_attempts_ip_ts")

    op.drop_table("login_attempts")
    op.drop_table("folders")
    op.drop_table("engines")
    op.drop_table("audit_log")
    op.drop_table("access_profiles")
    # ### end Alembic commands ###
